name: Scrape Queue

on:
  schedule:
    - cron: '0 6 * * *'  # This cron expression schedules the workflow to run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Pythob
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Setup Dependencies
      run: pip install -r requirements.txt

    - name: Scrape
      run: python moderator_queue.py

    - name: Commit results
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
